### ISSUE TITLE
ttlock not working after latest HASS update

### ISSUE THREAD

**Issue by imrj** [jbergler/hass-ttlock#112] opened 2024-05-06 11:17 UTC
The automation service fails to start after latest HASS Core update,  log attached. 
The App is properly setup on the TTLock API side, it has not changed (proper oauth ID and secret are valid as well as callback URL)
[ttlog-fail-log.txt](https://github.com/jbergler/hass-ttlock/files/15219862/ttlog-fail-log.txt)

Core 2024.5.1
Supervisor 2024.04.4
Operating System 12.2
Frontend 20240501.0

**Comment by jbergler** [comment] 2024-05-06 22:30
Duplicate of #107, please upgrade.

**Closed as not planned by jbergler** 2024-05-06 22:30 UTC
Labels: duplicate
