### ISSUE TITLE
Upgraded to 2024.5.0 and TTLock setup now fails

### ISSUE THREAD

**Issue by wjwnz** [jbergler/hass-ttlock#109] opened 2024-05-02 23:29 UTC
Upgraded to 2024.5.0 and TTLock setup now fails

```
Logger: homeassistant.setup
Source: setup.py:404
First occurred: 11:10:17 AM (1 occurrences)
Last logged: 11:10:17 AM

Error during setup of component ttlock
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 404, in _async_setup_component
    result = await task
             ^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ttlock/__init__.py", line 53, in setup
    Services(hass).register()
  File "/config/custom_components/ttlock/services.py", line 77, in register
    self.hass.services.async_register(
  File "/usr/src/homeassistant/homeassistant/core.py", line 2522, in async_register
    self._hass.verify_event_loop_thread("async_register")
  File "/usr/src/homeassistant/homeassistant/core.py", line 440, in verify_event_loop_thread
    frame.report(
  File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 162, in report
    _report_integration(what, integration_frame, level, error_if_integration)
  File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 203, in _report_integration
    raise RuntimeError(
RuntimeError: Detected that custom integration 'ttlock' calls async_register from a thread at custom_components/ttlock/services.py, line 77: self.hass.services.async_register(. Please report it to the author of the 'ttlock' custom integration.
```

## Diagnostic info

It wont let me pull diagnostics as its not loaded.

**Comment by jbergler** [comment] 2024-05-03 00:40
Dupe of #107, please upgrade

**Closed as not planned by jbergler** 2024-05-03 00:40 UTC
Labels: duplicate
