### ISSUE TITLE
Problems connecting to HA

### ISSUE THREAD

**Issue by ManRoumanis** [jbergler/hass-ttlock#104] opened 2024-03-12 18:14 UTC
## Describe the bug

I set up TTLock integration with HA. It works perfect for 1-2 days. After that it fails to setup or needs more time. After 2-3 more days fails continuisly. I have to delete the integration and start over . At the moment i have delete and reintall the integration 4 times.

## Diagnostic info

Please download the diagnostic info for tttlock from within Home Assistant and **attach** it to this ticket.
There are instructions on how to do this [here](https://www.home-assistant.io/integrations/diagnostics/)

**Comment by Mahalov24** [comment] 2024-03-13 07:34
https://euopen.ttlock.com/manager/ 
API calls this month max 5000 
Home assistant -> setting -> TTlock -> three dots -> System options ->
Disble polling for updates!!!

(If Home Assistant should automatically poll TTLock entities for updates.)

**Comment by ManRoumanis** [comment] 2024-03-13 09:58
Thank you very much. I changed the settings and inform you later if the problem is solved.

**Comment by jbergler** [comment] 2024-03-13 20:14
How many locks do you have in your account?
The 5000 requests/month limit isn't documented by ttlock, so this is news to me (but I only have a single lock)

Currently we poll for updates every 15minutes, which equates to approximately 2 requests per lock per update interval.
With 8 locks that would use up 5000 requests in approximately 3 days.

**Comment by Mahalov24** [comment] 2024-03-13 20:53
I was wrong
Basic
Monthly max API calls：300000
Max number of App：3
Price：Free

https://euopen.ttlock.com/user/information
<img width="1392" alt="Снимок экрана 2024-03-14 в 01 45 49" src="https://github.com/jbergler/hass-ttlock/assets/28709561/cea6a3a5-b4c2-4610-961f-fbddbfe3c3af">

**Comment by jbergler** [comment] 2024-03-15 05:19
I'm going to close this since it doesn't have the neccesary info to debug.
Please enable debug logs for the integration and reproduce the issue. The debug logging will be required to understand the behavior. 

I'm happy to re-open the issue if the necessary logs are attached.

**Closed as not planned by jbergler** 2024-03-15 05:18 UTC
Labels: invalid
